import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Providers from "./providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TravelTrucks",
  description: "Travel Trucks",
  icons: {
    icon: "/favicon.ico",
  },
  openGraph: {
    title: "Travel Trucks",
    description: "Generated by create next app",
    url: "https://travel-trucks.vercel.app/",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.variable} suppressHydrationWarning>
        <div className="container">
          <Header />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
